gText_Birch_Welcome::
.string "Welcome to the world of Pokémon!\l"
.string "I'm Professor Birch.\p"
.string "$"

gText_Birch_Pokemon::
.string "This is what we call a “Pokémon.”\p"
.string "\n"
.string "$"

gText_Birch_MainSpeech::
.string "5 years ago, events orchestrated by the\n"
.string "organisation known as Team Magma led\l"
.string "to the eruption of Mt Chimney.\p"
.string "This destroyed much of Hoenn and.\n"
.string "devastated many lives.\p"
.string "People across the region are supporting\n"
.string "the reconstruction efforts and\l"
.string "helping any affected however they can.\p"
.string "$"

gText_Birch_AndYouAre::
.string "And you are?$"

gText_Birch_BoyOrGirl::
.string "Are you a boy?\n"
.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
.string "All right.\n"
.string "What's your name?$"

gText_Birch_SoItsPlayer::
.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
.string "Ah, okay!\p"
.string "You're {PLAYER}{KUN} who's about to start their\n"
.string "adventure in Dewford Town.\l"
.string "I get it now!\p"
.string "$"

gText_Birch_AreYouReady::
.string "All right, are you ready?\p"
.string "I have sent some Pokémon for you to\n"
.string "your local Gym Leader, Brawly.\p"
.string "Come see me in my Lab when you have\n"
.string "the opportunity.\p"
.string "I live in Littleroot, so it isn't too\n"
.string "far away.\p"
.string "GOOD LUCK!\p"
.string "$"

